django/learning_users/basic_app/urls.py
from django.urls import path
from basic_app import views

# TEMPLATE URLS!
app_name = 'basic_app'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
]

django/learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from basic_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('basic_app/',include('basic_app.urls')),
    path('admin/', admin.site.urls),
    path('favicon.ico',RedirectView.as_view(url='static/images/favicon.ico'))
]

django/learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User,models.CASCADE)

    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

django/learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

django/learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app import forms

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = forms.UserForm(data=request.POST)
        profile_form = forms.UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() & profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = forms.UserForm()
        profile_form = forms.UserProfileInfoForm()

    context_dict = {'user_form':user_form,'profile_form':profile_form,'registered':registered}
    return render(request,'basic_app/register.html',context=context_dict)

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')
        else:
            print('Someone tried to login and failed!')
            print('Username: {} - and password: {}'.format(username,password))
            return HttpResponse('INVALID LOGIN DETAILS SUPPLIED')

    return render(request,'basic_app/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse('Cool, you are logged in!')

django/learning_users/templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>MY APP</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
  </head>
  <body>
    <nav class='navbar navbar-default navbar-static-top'>
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>
          <!-- <li><a class="navbar-link" href="{% url 'basic_app:special' %}">Special Page (only if logged in!)</a></li> -->
          {% if user.is_authenticated %}
          <li><a class="navbar-link" href="{% url 'basic_app:logout' %}">Log Out</a></li>
          {% else %}
          <li><a class="navbar-link" href="{% url 'basic_app:login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      <div class="jumbotron">
        {% block body_block %}
        {% endblock %}
      </div>
    </div>
  </body>
</html>

django/learning_users/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}

{% block body_block %}

<h1>User Exercise Index Page</h1>

{% endblock %}

django/learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

<h1>Please Login</h1>
<form action="{% url 'basic_app:login' %}" method="post">
  {% csrf_token %}
  <label for="username">Username</label>
  <input type="text" name="username" placeholder="Enter Username">

  <label for="password">Password:</label>
  <input type="password" name="password">

  <input type="submit" value="Login">
</form>

{% endblock %}

django/learning_users/templates/basic_app/register.html
{% extends "basic_app/base.html" %}

{% block body_block %}

{% if registered %}
  <h1>Thank you for registering!</h1>
{% else %}
  <h1>Register Here!</h1>
  <h3>Fill out the form:</h3>

  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" value="Register">
  </form>
{% endif %}

{% endblock %}