django/CBVs_project/CBVs_project/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('basic_app/',include('basic_app.urls'),name='basic_app'),
    path('admin/', admin.site.urls),
]

django/CBVs_project/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('schools/',views.SchoolListView.as_view(),name='list'),
    path('schools/<int:pk>/',views.SchoolDetailView.as_view(),name='detail'),
    path('create/',views.SchoolCreateView.as_view(),name='create'),
    path('update/<int:pk>/',views.SchoolUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',views.SchoolDeleteView.as_view(),name='delete'),
]

django/CBVs_project/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    # where to go after creating new School via CreateView
    def get_absolute_url(self):
        return reverse('basic_app:detail',kwargs={'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,models.CASCADE,related_name='students')

    def __str__(self):
        return self.name

django/CBVs_project/basic_app/views.py
from django.shortcuts import render
from django.views.generic import (View,TemplateView,ListView,DetailView,
                                    CreateView,UpdateView,DeleteView)
from django.http import HttpResponse
from django.urls import reverse_lazy
from basic_app import models

# Create your views here.
# def index(request):
#     return render(request,'index.html')

class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['hello'] = 'Hello world!'
        return context

class SchoolListView(ListView):
    model = models.School

class SchoolDetailView(DetailView):
    model = models.School
    template_name = 'basic_app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ['name','principal','location']
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ['name','principal']
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy('basic_app:list')

django/CBVs_project/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>MY APP</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  </head>
  <body>

    <nav class='navbar navbar-default navbar-static-top'>
      <ul class='nav navbar-nav'>
        <li><a class='navbar-brand' href='{% url 'basic_app:list' %}'>Schools</a></li>
        <li><a class='navbar-link' href='{% url 'admin:index' %}'>Admin</a></li>
        <li><a href="#"></a></li>
      </ul>
    </nav>

    <div class="container">
      <div class="jumbotron">
        {% block body_block %}
        {% endblock %}
      </div>
    </div>
  </body>
</html>

django/CBVs_project/basic_app/templates/basic_app/school_confirm_delete.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}

<h1>Delete {{school.name}}?</h1>
<form method="post">
  {% csrf_token %}
  <input type="submit" class='btn btn-danger' value="Delete">
  <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
</form>

{% endblock %}

django/CBVs_project/basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}

<h1>Welcome to the School Detail Page</h1>
<h2>School details:</h2>
<p>Name: {{ school.name }}</p>
<p>Principal: {{ school.principal }}</p>
<p>Location: {{ school.location }}</p>

<h3>Students:</h3>

{% for student in school.students.all %}
  <p>{{student.name}} who is {{student.age}} years old.</p>
{% empty %}
  <p>No students in this school.</p>
{% endfor %}

<div class="container">
  <p><a class='btn btn-warning' href="{% url 'basic_app:update' pk=school.pk %}">Update</a></p>
</div>

{% endblock %}

django/CBVs_project/basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}

<h1>
  {% if not form.instance.pk %}
  Create School
  {% else %}
  Update School
  {% endif %}
</h1>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-primary" value="Submit">
</form>

{% endblock %}

django/CBVs_project/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}

<h1>Welcome to a list of all the schools!</h1>
<ol>
  {% for school in school_list %}
  <h2><li><a href="{{school.id}}">{{ school.name }}</a></li></h2>
  {% endfor %}
</ol>

{% endblock %}

django/CBVs_project/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>MY APP</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  </head>
  <body>
    <div class="container">
      <div class="jumbotron">
        {% block body_block %}
        {% endblock %}
      </div>
    </div>
  </body>
</html>

django/CBVs_project/templates/index.html
{% extends "base.html" %}
{% block body_block %}
<h1>Home Page!</h1>
{% endblock %}