django/learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

# TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns = [
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other'),
]

django/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import include, path
from basic_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('basic_app/',include('basic_app.urls')),
    path('admin/', admin.site.urls),
]

django/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'basic_app/index.html',context=context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

django/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">HOME</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      <div class="jumbotron">
        {% block body_block %}
        <!-- Anything outside of this will be inherited if you extend! -->
        {% endblock %}
      </div>
    </div>


  </body>
</html>

django/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load my_extras %}
  {% block body_block %}
    <h1>Welcome to the index page!</h1>
    <a href="basic_app/relative">RELATIVE PAGE</a>
    <h3>{{ text | upper }}</h3>
    <h3>{{ text | cutty:"world" }}</h3>
    <h3>{{ number | add:"99" }}</h3>
  {% endblock %}

django/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to the other page!</h1>
    <h2>This is an example of template inheritance</h2>
  {% endblock %}

django/learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>REL-URL-TEMP</title>
  </head>
  <body>
    <h1>Welcome to the relative url templates page!</h1>
    <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
    <br>
    <!-- MIGRATE BEFORE ADMIN LINK WORKS -->
    <a href="{% url 'admin:index' %}">THE ADMIN PAGE</a>
    <br>
    <a href="{% url 'index' %}">THE INDEX PAGE</a>
  </body>
</html>